### PR TITLE
Palindrome future 

### PR DESCRIPTION
**Pull request by SvetlanaMik**
Can you please check it out and possibly approve it

### CODE REVIEW

**Comment by michaelakkawi** [comment]
Michael approves

**Review by michaelakkawi — APPROVED** [review]
Approved by Michael Akkawi

**Review by Mendbayart — APPROVED** [review]
Great Palindrome code! great job Lana definitely approved!

**Review by Zalinalina — COMMENTED** [review]
Great job!

**Review by Zalinalina — APPROVED** [review]

**Pull request merged**
