### PR TITLE
tc2-bahar

### PR DESCRIPTION
**Pull request by jbahar**
please review my code

### CODE REVIEW

**Comment by ziba84** [comment]
good job

**Review by Mendbayart — APPROVED** [review]
amazing!

**Review by ziba84 — APPROVED** [review]
good job

**Review by Ainur519 — APPROVED** [review]
You did great

**Review by jbahar — COMMENTED** [review]
hi friends my first commit

**Review by SvetlanaMik — APPROVED** [review]

**Review by Zalinalina — APPROVED** [review]

**Review by Zalinalina — COMMENTED** [review]
Good job!

**Pull request merged**
